f1 = input(" enter f1 name ")
f2 = input(" enter f2 name ")
a = open(f1,"r")
data1 = a.read()
b = open(f2,"r")
data2 = b.read()
c = open(f1,"w")
c.write(data2)
d = open(f2,"w")
d.write(data1)